### PR TITLE
review

### PR DESCRIPTION
**Pull request by Logan676**
@forouher thanks for your excellent work, I have discussed the user requirements of the document provider for several times, the project manager suggest to remove the account list, see the edited screenshot below. 
remove_safile_account_list copy

What\`s more, the old uploading module supports **multi files uploading** which is an important feature in Seafile, but seems that this document provider doesn`t supported that any more. 

So dose the SAF supports multi files uploading and do you have any idea of how to implement that? 
Please let me know if you have any problems, thanks.

### CODE REVIEW

**Comment by forouher** [comment]
Regarding the account list:

So the new layout should be:

...
Recent
Seafile
Images
 ...

And the account are then listed inside the "Seafile" item?

**Comment by forouher** [comment]
regarding multi file upload:

Kitkat should support that: https://developer.android.com/reference/android/content/Intent.html#EXTRA_ALLOW_MULTIPLE

I'll have a look into it.

**Comment by Logan676** [comment]
> And the account are then listed inside the "Seafile" item?
@forouher  no, we don\`t need a list, only current account (one account) is ok.

Because it\`s weird to pick files from one Seafile account to another, so that we should remove (or simply hide them if you don\`t want to delete the source code on which you have spent quite a lot of time) the account list.

**Comment by forouher** [comment]
@Logan676 I don't mind deleting the code, but do you think that this is best choice regarding usability?

I would always only be able to access the seafile account which is currently selected in the Seafile app.

Say I'm in some other app, and I want to fetch a file from Seafile. A simple example would be adding an email attachment in gmail. If the file I want to select is not in the currently active Seafile account, I would have to

- exit the current app
- open the Seafile app
- switch the account
- go back to app I was using

I'd argue that this would be making this process more complicated than necessary.

**Comment by Logan676** [comment]
Right, the scenario above is using other apps to pick files from Seafile, which is different with what I argued above. 
So can we distinct the two and implement them separately. 

Let say, 
* scenario one
 - you are in Seafile
 - you want to pick files from other apps
 - open the document provider 
 - shows current one account only
* scenario two
 - you are in other app, e.g. Gmail
 - you want to pick attachments from Seafile
 - open the document provider 
 - show all available account list of Seafile

Is that possible?

**Comment by forouher** [comment]
I doubt it. Both scenarios invoke the ACTION_GET_CONTENT intent. And there is only very limited room to influence the file picker by the caller. According to

https://developer.android.com/reference/android/content/Intent.html#ACTION_GET_CONTENT

we can
- limit the file picker to only select certain mime types
- only show local (non-network) sources

And that's about it.

**Comment by Logan676** [comment]
@forouher then just go ahead and ignore that requirements.

**Comment by freeplant** [comment]
When a user click the upload menu in Seafile, it is better to "only show local (non-network) sources". This  will be consistent will current functionality.

Uploading a file in Seafile into a folder in Seafile is strange, which will cause confusing to users.

**Comment by forouher** [comment]
@freeplant good idea, yes. I didn't think of that. Appended a patch doing this  to the pull request https://github.com/haiwen/seadroid/issues/306

**Pull request merged**
